// wrap.go — Copilot / local IDE mode only.
//
// Reads .vscode/mcp.json, patches every MCP server URL or stdio command to
// route through PerchGuard, and restores the original file on exit.
// Triggered by --mode=wrap; not used in server or autonomous-agent mode.
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/Droshow/PerchGuard/perchguard/pkg/envutil"
)

// mcpConfigFile is the VS Code / Copilot MCP configuration schema we read and patch.
type mcpConfigFile struct {
	Servers map[string]mcpServerDef `json:"servers"`
}

type mcpServerDef struct {
	// HTTP-based server
	URL string `json:"url,omitempty"`
	// stdio-based server
	Type    string            `json:"type,omitempty"`
	Command string            `json:"command,omitempty"`
	Args    []string          `json:"args,omitempty"`
	Env     map[string]string `json:"env,omitempty"`
	// shared
	Headers map[string]string `json:"headers,omitempty"`
}

// setupWrap reads the MCP config at configPath, picks the upstream, patches all
// HTTP server URLs to route through PerchGuard, and returns a cleanup func that
// restores the original file on exit (call it from a signal handler AND defer).
func setupWrap(configPath string) func() {
	if configPath == "" {
		configPath = findMCPConfig()
	}
	if configPath == "" {
		scaffoldMCPConfig()
		log.Fatal("[wrap] created .vscode/mcp.json — edit it with your MCP server details, then re-run: perchguard --mode=wrap")
	}

	raw, err := os.ReadFile(configPath)
	if err != nil {
		log.Fatalf("[wrap] read %s: %v", configPath, err)
	}

	var cfg mcpConfigFile
	if err := json.Unmarshal(raw, &cfg); err != nil {
		log.Fatalf("[wrap] parse %s: %v", configPath, err)
	}

	// Determine HTTP upstream (if any). PERCHGUARD_MCP_UPSTREAM env var wins.
	// stdio servers are wrapped separately (see patching loop below).
	httpUpstream := os.Getenv("PERCHGUARD_MCP_UPSTREAM")
	var upstreamName string
	for name, srv := range cfg.Servers {
		if srv.URL != "" && httpUpstream == "" {
			httpUpstream = srv.URL
			upstreamName = name
		} else if srv.URL != "" && srv.URL == httpUpstream {
			upstreamName = name
		}
	}
	if httpUpstream != "" {
		os.Setenv("PERCHGUARD_MCP_UPSTREAM", httpUpstream)
	}

	if os.Getenv("PERCHGUARD_POLICY") == "" {
		if p := findPolicyPath("copilot-profile.yaml"); p != "" {
			os.Setenv("PERCHGUARD_POLICY", p)
		}
	}

	pgAddr := envutil.GetEnv("PERCHGUARD_ADDR", ":8080")
	host := "localhost"
	if !strings.HasPrefix(pgAddr, ":") {
		// addr is host:port
		parts := strings.SplitN(pgAddr, ":", 2)
		host = parts[0]
		pgAddr = ":" + parts[1]
	}
	pgURL := fmt.Sprintf("http://%s%s/mcp", host, pgAddr)

	// Patch all servers to route through PerchGuard:
	// • HTTP servers: rewrite URL to the PerchGuard /mcp endpoint.
	// • stdio servers: rewrite command to `perchguard --mode=mcp-proxy`;
	//   the original command is passed via PERCHGUARD_UPSTREAM_CMD/ARGS env vars.
	pgBin, _ := exec.LookPath("perchguard")
	if pgBin == "" {
		pgBin = "perchguard" // rely on PATH at VS Code launch time
	}
	policyPath := os.Getenv("PERCHGUARD_POLICY")

	patched := mcpConfigFile{Servers: make(map[string]mcpServerDef, len(cfg.Servers))}
	stdioWrapped := 0
	for name, srv := range cfg.Servers {
		switch {
		case srv.URL != "":
			// HTTP server — redirect to PerchGuard HTTP proxy.
			srv.URL = pgURL
		case srv.Command != "" || srv.Type == "stdio":
			// stdio server — launch perchguard as the subprocess; it will
			// start the original command internally via SubprocessTransport.
			env := srv.Env
			if env == nil {
				env = make(map[string]string)
			}
			env["PERCHGUARD_UPSTREAM_CMD"] = srv.Command
			if len(srv.Args) > 0 {
				argsJSON, _ := json.Marshal(srv.Args)
				env["PERCHGUARD_UPSTREAM_ARGS"] = string(argsJSON)
			}
			if policyPath != "" {
				env["PERCHGUARD_POLICY"] = policyPath
			}
			env["PERCHGUARD_AGENT_ROLE"] = envutil.GetEnv("PERCHGUARD_AGENT_ROLE", "developer_agent")
			srv = mcpServerDef{
				Type:    "stdio",
				Command: pgBin,
				Args:    []string{"--mode=mcp-proxy"},
				Env:     env,
			}
			stdioWrapped++
			log.Printf("[wrap] stdio server %q → wrapped via subprocess", name)
		}
		patched.Servers[name] = srv
	}
	if httpUpstream == "" && stdioWrapped == 0 {
		log.Fatal("[wrap] mcp.json has no HTTP or stdio servers to wrap — check the file format")
	}

	patchedBytes, err := json.MarshalIndent(patched, "", "  ")
	if err != nil {
		log.Fatalf("[wrap] marshal patched config: %v", err)
	}
	patchedBytes = append(patchedBytes, '\n')

	if err := os.WriteFile(configPath, patchedBytes, 0644); err != nil {
		log.Fatalf("[wrap] write patched config: %v", err)
	}

	// Banner ----------------------------------------------------------------
	apiKey := os.Getenv("PERCHGUARD_API_KEY")
	keyHint := apiKey
	if keyHint == "" {
		keyHint = "<auto-generated — see first log line>"
	}
	policy := envutil.GetEnv("PERCHGUARD_POLICY", "<default>")

	width := 62
	line := func(label, value string) string {
		content := fmt.Sprintf("  %-12s %s", label, value)
		pad := width - len(content) - 1
		if pad < 0 {
			pad = 0
		}
		return "│" + content + strings.Repeat(" ", pad) + "│"
	}
	bar := "├" + strings.Repeat("─", width) + "┤"
	top := "┌" + strings.Repeat("─", width) + "┐"
	bot := "└" + strings.Repeat("─", width) + "┘"
	title := "│" + fmt.Sprintf("%-*s", width, "  PerchGuard — wrap mode") + "│"

	fmt.Println()
	fmt.Println(top)
	fmt.Println(title)
	fmt.Println(bar)
	fmt.Println(line("upstream:", func() string {
		if httpUpstream != "" {
			return httpUpstream
		}
		return fmt.Sprintf("%d stdio server(s) wrapped", stdioWrapped)
	}()))
	if upstreamName != "" {
		fmt.Println(line("server:", upstreamName))
	}
	fmt.Println(line("proxy:", pgURL))
	fmt.Println(line("config:", configPath))
	fmt.Println(line("policy:", policy))
	fmt.Println(line("api key:", keyHint))
	fmt.Println(bar)
	fmt.Println(line("", ".vscode/mcp.json patched — Copilot calls now"))
	fmt.Println(line("", "flow through PerchGuard. Ctrl-C restores it."))
	fmt.Println(bar)
	meterCmd := fmt.Sprintf("perchguard --mode=meter --watch-addr http://%s%s", host, pgAddr)
	if apiKey != "" {
		meterCmd += " --watch-key " + apiKey
	}
	fmt.Println(line("meter:", meterCmd))
	fmt.Println(bot)
	fmt.Println()

	// Restore function — idempotent (safe to call twice).
	restored := false
	return func() {
		if restored {
			return
		}
		restored = true
		if err := os.WriteFile(configPath, raw, 0644); err != nil {
			log.Printf("[wrap] WARNING: could not restore %s: %v", configPath, err)
		} else {
			log.Printf("[wrap] restored %s", configPath)
		}
	}
}

// findMCPConfig searches the current directory and its parent for .vscode/mcp.json.
func findMCPConfig() string {
	cwd, _ := os.Getwd()
	for dir := cwd; ; dir = filepath.Dir(dir) {
		candidate := filepath.Join(dir, ".vscode", "mcp.json")
		if _, err := os.Stat(candidate); err == nil {
			return candidate
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break // reached filesystem root
		}
	}
	return ""
}

// scaffoldMCPConfig creates a template .vscode/mcp.json in the current directory
// when no config is found. The template covers both HTTP and stdio server shapes
// so the developer only needs to fill in their specific server details.
func scaffoldMCPConfig() {
	cwd, _ := os.Getwd()
	vscodDir := filepath.Join(cwd, ".vscode")
	if err := os.MkdirAll(vscodDir, 0755); err != nil {
		log.Fatalf("[wrap] cannot create .vscode/: %v", err)
	}
	dest := filepath.Join(vscodDir, "mcp.json")

	// Template shows the two supported server shapes.
	// Only one is needed — delete the example that doesn't apply.
	template := `{
  "servers": {
    "my-http-server": {
      "url": "http://localhost:3000",
      "_hint": "HTTP-based MCP server — replace URL, then run: perchguard --mode=wrap"
    },
    "my-stdio-server": {
      "type": "stdio",
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-filesystem", "/path/to/workspace"],
      "_hint": "stdio MCP server — replace command/args, then run: perchguard --mode=wrap"
    }
  }
}
`
	if err := os.WriteFile(dest, []byte(template), 0644); err != nil {
		log.Fatalf("[wrap] cannot write template %s: %v", dest, err)
	}
	fmt.Printf("\n  Created: %s\n\n", dest)
	fmt.Println("  Edit the file above:")
	fmt.Println("  \u2022 For an HTTP MCP server: set the correct URL under 'my-http-server'.")
	fmt.Println("  \u2022 For a stdio MCP server: set command + args under 'my-stdio-server'.")
	fmt.Println("  \u2022 Delete the example that doesn\u2019t apply.")
	fmt.Println("  Then re-run:  perchguard --mode=wrap")
	fmt.Println()
}
