apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "perchguard.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "perchguard.labels" . | nindent 4 }}
  annotations:
    {{- if and .Values.aws.enabled .Values.aws.irsaRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.aws.irsaRoleArn | quote }}
    {{- end }}
