//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentIsolationPolicy) DeepCopyInto(out *AgentIsolationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentIsolationPolicy.
func (in *AgentIsolationPolicy) DeepCopy() *AgentIsolationPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentIsolationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentIsolationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentIsolationPolicyList) DeepCopyInto(out *AgentIsolationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentIsolationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentIsolationPolicyList.
func (in *AgentIsolationPolicyList) DeepCopy() *AgentIsolationPolicyList {
	if in == nil {
		return nil
	}
	out := new(AgentIsolationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentIsolationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentIsolationPolicySpec) DeepCopyInto(out *AgentIsolationPolicySpec) {
	*out = *in
	in.WorkloadSelector.DeepCopyInto(&out.WorkloadSelector)
	in.Egress.DeepCopyInto(&out.Egress)
	out.Sandbox = in.Sandbox
	out.SourceConfigRef = in.SourceConfigRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentIsolationPolicySpec.
func (in *AgentIsolationPolicySpec) DeepCopy() *AgentIsolationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AgentIsolationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentIsolationPolicyStatus) DeepCopyInto(out *AgentIsolationPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworkPoliciesApplied != nil {
		in, out := &in.NetworkPoliciesApplied, &out.NetworkPoliciesApplied
		*out = new(NetworkPolicyStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CiliumNetworkPoliciesApplied != nil {
		in, out := &in.CiliumNetworkPoliciesApplied, &out.CiliumNetworkPoliciesApplied
		*out = new(NetworkPolicyStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentIsolationPolicyStatus.
func (in *AgentIsolationPolicyStatus) DeepCopy() *AgentIsolationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AgentIsolationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressPolicy) DeepCopyInto(out *EgressPolicy) {
	*out = *in
	if in.AllowedDestinations != nil {
		in, out := &in.AllowedDestinations, &out.AllowedDestinations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BlockedDestinations != nil {
		in, out := &in.BlockedDestinations, &out.BlockedDestinations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedPorts != nil {
		in, out := &in.AllowedPorts, &out.AllowedPorts
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressPolicy.
func (in *EgressPolicy) DeepCopy() *EgressPolicy {
	if in == nil {
		return nil
	}
	out := new(EgressPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicyStatus) DeepCopyInto(out *NetworkPolicyStatus) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicyStatus.
func (in *NetworkPolicyStatus) DeepCopy() *NetworkPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxPolicy) DeepCopyInto(out *SandboxPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxPolicy.
func (in *SandboxPolicy) DeepCopy() *SandboxPolicy {
	if in == nil {
		return nil
	}
	out := new(SandboxPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceConfigRef) DeepCopyInto(out *SourceConfigRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceConfigRef.
func (in *SourceConfigRef) DeepCopy() *SourceConfigRef {
	if in == nil {
		return nil
	}
	out := new(SourceConfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSelector) DeepCopyInto(out *WorkloadSelector) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSelector.
func (in *WorkloadSelector) DeepCopy() *WorkloadSelector {
	if in == nil {
		return nil
	}
	out := new(WorkloadSelector)
	in.DeepCopyInto(out)
	return out
}
